/// Flutter icons PrayerIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PrayerIcons
///      fonts:
///       - asset: fonts/PrayerIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PrayerIcons {
  PrayerIcons._();

  static const _kFontFam = 'PrayerIcons';
  static const _kFontPkg = null;

  static const IconData fashion_1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
