/// Flutter icons SunsetIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SunsetIcons
///      fonts:
///       - asset: fonts/SunsetIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SunsetIcons {
  SunsetIcons._();

  static const _kFontFam = 'SunsetIcons';
  static const _kFontPkg = null;

  static const IconData cloudy_2 = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sky_1 = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun_1 = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sunrise = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sunrise_1 = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sunset = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
